//
//  ObjcHeaderCGGenerator.swift
//  cggen
//
//  Created by Alexander Skvortsov on 10/01/2018.
//

import CoreGraphics

struct ObjcHeaderCGGenerator: CoreGraphicsGenerator {
  let prefix: String
  func filePreamble() -> String {
    return [
      "// Generated by cggen",
      "",
      "#import <CoreGraphics/CoreGraphics.h>",
      "\n",
      ].joined(separator: "\n")
  }

  func command(step _: DrawStep, gradients _: [String: Gradient]) -> [String] {
    return []
  }

  func funcStart(imageName: ImageName, imageSize: CGSize) -> [String] {
    let camel = imageName.camelCase
    return [
      "static const CGSize k\(prefix)\(camel)ImageSize = (CGSize){.width = \(imageSize.width), .height = \(imageSize.height)};",
      ObjCGen.functionDecl(imageName: camel, prefix: prefix),
    ]
  }

  func funcEnd(imageName _: ImageName, imageSize _: CGSize) -> [String] {
    return []
  }

  func fileEnding() -> String {
    return ""
  }
}
