// Copyright (c) 2018 Yandex LLC. All rights reserved.
// Author: Alexander Skvortsov <askvortsov@yandex-team.ru>

import CoreGraphics

struct ObjcHeaderCGGenerator: CoreGraphicsGenerator {
  let prefix: String
  func filePreamble() -> String {
    return [
      "// Generated by cggen",
      "",
      "#import <CoreGraphics/CoreGraphics.h>",
      "\n",
      ].joined(separator: "\n")
  }

  func generateImageFunction(image: Image) -> String {
    let camel = image.name.camelCase
    let imageSize = image.route.boundingRect.size
    return
      """
      static const CGSize k\(prefix)\(camel)ImageSize = (CGSize){.width = \(imageSize.width), .height = \(imageSize.height)};
      \(ObjCGen.functionDecl(imageName: camel, prefix: prefix))
      """
  }

  func fileEnding() -> String {
    return ""
  }
}
