// Generated by cggen


void runMergedBytecode(CGContextRef context, const uint8_t* arr, int decompressedLen, int compressedLen, int startIndex, int endIndex);
void runPathBytecode(CGMutablePathRef path, const uint8_t* arr, int len);
void runMergedPathBytecode(CGMutablePathRef path, const uint8_t* arr, int decompressedLen, int compressedLen, int startIndex, int endIndex);

static const uint8_t mergedBytecodes[];

void testDrawCircleImageInContext(CGContextRef context) {
  runMergedBytecode(context, mergedBytecodes, 275, 157, 0, 65);
}

void testDrawSquareImageInContext(CGContextRef context) {
  runMergedBytecode(context, mergedBytecodes, 275, 157, 66, 139);
}

void testDrawStarImageInContext(CGContextRef context) {
  runMergedBytecode(context, mergedBytecodes, 275, 157, 140, 274);
}

static const uint8_t mergedBytecodes[] = {
  98, 118, 120, 110, 19, 1, 0, 0, 141, 0, 0, 0, 96, 1, 0, 230, 25, 0, 0, 128, 63, 0, 249, 152, 8, 128, 191, 228, 72, 66, 0, 27, 243, 238, 64, 35, 52, 152, 219, 32, 44, 62, 80, 22, 0, 0, 160, 64, 24, 4, 142, 32, 66, 200, 1, 23, 1, 0, 243, 56, 66, 253, 110, 32, 232, 231, 76, 60, 32, 192, 57, 43, 6, 250, 152, 4, 240, 65, 24, 16, 56, 74, 240, 7, 110, 112, 233, 241, 196, 15, 32, 230, 126, 34, 10, 10, 16, 23, 40, 66, 64, 144, 20, 64, 12, 176, 96, 8, 92, 70, 40, 64, 4, 12, 64, 8, 60, 152, 40, 80, 66, 8, 20, 152, 16, 80, 65, 152, 32, 144, 65, 8, 60, 8, 48, 233, 184, 65, 0, 0, 176, 65, 8, 23, 1, 6, 0, 0, 0, 0, 0, 0, 0, 98, 118, 120, 36
};
