// Generated by cggen

#if __has_feature(modules)
@import CoreGraphics;
#else  // __has_feature(modules)
#import <CoreGraphics/CoreGraphics.h>
#endif  // __has_feature(modules)

static const CGSize ktestCircleImageSize = (CGSize){.width = 50.0, .height = 50.0};
void testDrawCircleImageInContext(CGContextRef context);

static const CGSize ktestSquareImageSize = (CGSize){.width = 40.0, .height = 40.0};
void testDrawSquareImageInContext(CGContextRef context);

static const CGSize ktestStarImageSize = (CGSize){.width = 60.0, .height = 60.0};
void testDrawStarImageInContext(CGContextRef context);

