// Generated by cggen


void runMergedBytecode(CGContextRef context, const uint8_t* arr, int decompressedLen, int compressedLen, int startIndex, int endIndex);
void runPathBytecode(CGMutablePathRef path, const uint8_t* arr, int len);
void runMergedPathBytecode(CGMutablePathRef path, const uint8_t* arr, int decompressedLen, int compressedLen, int startIndex, int endIndex);

static const uint8_t mergedBytecodes[];

void testDrawPathsImageInContext(CGContextRef context) {
  runMergedBytecode(context, mergedBytecodes, 369, 217, 0, 63);
}

void testSimpleArrowPath(CGMutablePathRef path) {
  runMergedPathBytecode(path, mergedBytecodes, 369, 217, 64, 117);
}

void testSimpleHeartPath(CGMutablePathRef path) {
  runMergedPathBytecode(path, mergedBytecodes, 369, 217, 118, 277);
}

void testSimpleStarPath(CGMutablePathRef path) {
  runMergedPathBytecode(path, mergedBytecodes, 369, 217, 278, 368);
}

static const uint8_t mergedBytecodes[] = {
  98, 118, 120, 110, 113, 1, 0, 0, 201, 0, 0, 0, 96, 1, 0, 230, 25, 0, 0, 128, 63, 0, 249, 152, 8, 128, 191, 239, 200, 66, 0, 35, 255, 255, 255, 31, 10, 215, 35, 60, 48, 5, 0, 48, 1, 136, 4, 200, 66, 192, 12, 23, 49, 1, 235, 160, 65, 0, 0, 72, 66, 2, 0, 0, 140, 66, 8, 9, 110, 0, 0, 18, 64, 9, 112, 104, 18, 32, 249, 78, 112, 8, 41, 200, 9, 200, 65, 1, 242, 152, 40, 112, 65, 230, 160, 64, 0, 0, 240, 65, 8, 8, 88, 88, 1, 8, 17, 152, 33, 32, 65, 241, 96, 50, 65, 8, 9, 152, 58, 12, 66, 104, 8, 150, 241, 104, 17, 1, 242, 152, 33, 180, 66, 8, 8, 16, 50, 8, 9, 8, 67, 152, 83, 160, 66, 80, 8, 140, 88, 139, 1, 8, 17, 40, 133, 8, 8, 200, 160, 200, 65, 6, 243, 152, 196, 32, 65, 243, 88, 69, 2, 16, 9, 70, 130, 78, 112, 24, 108, 88, 45, 2, 72, 9, 140, 152, 18, 200, 65, 241, 104, 36, 12, 8, 173, 16, 54, 231, 32, 66, 0, 0, 32, 66, 6, 6, 0, 0, 0, 0, 0, 0, 0, 98, 118, 120, 36
};
