// Copyright (c) 2018 Yandex LLC. All rights reserved.
// Author: Alexander Skvortsov <askvortsov@yandex-team.ru>

import Base
import CoreGraphics

let commonHeaderPrefix = ObjcTerm.comment("Generated by cggen")
typealias RGBACGColor = RGBAColor<CGFloat>
