name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v2
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Enable Xcode prebuilts
      run: defaults write com.apple.dt.Xcode IDEPackageEnablePrebuilts YES
    - name: Build
      run: swift build -v --enable-experimental-prebuilts
    - name: Run tests
      run: SWIFT_DETERMINISTIC_HASHING=1 swift test -v --parallel
    - name: Build Demo for macOS
      run: xcodebuild -project Demo/Demo.xcodeproj -scheme Demo -configuration Release -destination 'platform=macOS' -skipMacroValidation build
    - name: Build Demo for iOS Simulator
      run: xcodebuild -project Demo/Demo.xcodeproj -scheme Demo -configuration Release -destination 'generic/platform=iOS Simulator' -skipMacroValidation build
    - name: Build CGGenRuntime for iOS
      run: xcodebuild -scheme CGGenRuntime -destination 'generic/platform=iOS' -skipMacroValidation build -quiet
