// Generated by cggen

#if __has_feature(modules)
@import CoreGraphics;
#else  // __has_feature(modules)
#import <CoreGraphics/CoreGraphics.h>
#endif  // __has_feature(modules)

static const CGSize kgrad_determGradientDeterminismTestImageSize = (CGSize){.width = 200.0, .height = 200.0};
void grad_determDrawGradientDeterminismTestImageInContext(CGContextRef context);

