// Generated by cggen

#if __has_feature(modules)
@import CoreGraphics;
#else  // __has_feature(modules)
#import <CoreGraphics/CoreGraphics.h>
#endif  // __has_feature(modules)

static const CGSize kmixedPathsAndImagesImageSize = (CGSize){.width = 100.0, .height = 100.0};
void mixedDrawPathsAndImagesImageInContext(CGContextRef context);

void mixedDiamondPath(CGMutablePathRef path);

void mixedHexagonPath(CGMutablePathRef path);

void mixedTrianglePath(CGMutablePathRef path);

