// Generated by cggen

#if __has_feature(modules)
@import CoreGraphics;
#else  // __has_feature(modules)
#import <CoreGraphics/CoreGraphics.h>
#endif  // __has_feature(modules)

static const CGSize ktestPathsImageSize = (CGSize){.width = 100.0, .height = 100.0};
void testDrawPathsImageInContext(CGContextRef context);

void testSimpleArrowPath(CGMutablePathRef path);

void testSimpleHeartPath(CGMutablePathRef path);

void testSimpleStarPath(CGMutablePathRef path);

