// Generated by cggen

#if __has_feature(modules)
@import CoreGraphics;
#else  // __has_feature(modules)
#import <CoreGraphics/CoreGraphics.h>
#endif  // __has_feature(modules)

static const CGSize kpdf_extgstate_determExtgstateMultipleParamsImageSize = (CGSize){.width = 200.0, .height = 200.0};
void pdf_extgstate_determDrawExtgstateMultipleParamsImageInContext(CGContextRef context);

