// Generated by cggen

#if __has_feature(modules)
@import CoreGraphics;
#else  // __has_feature(modules)
#import <CoreGraphics/CoreGraphics.h>
#endif  // __has_feature(modules)

static const CGSize kplugin_demoCircleImageSize = (CGSize){.width = 50.0, .height = 50.0};
void plugin_demoDrawCircleImageInContext(CGContextRef context);

static const CGSize kplugin_demoSquareImageSize = (CGSize){.width = 40.0, .height = 40.0};
void plugin_demoDrawSquareImageInContext(CGContextRef context);

static const CGSize kplugin_demoStarImageSize = (CGSize){.width = 60.0, .height = 60.0};
void plugin_demoDrawStarImageInContext(CGContextRef context);

